services:
  # Qdrant service for Vector DB
    # qdrant:
    #     image: qdrant/qdrant:latest
    #     container_name: my_qdrant
    #     restart: always
    #     ports:
    #         - "6333:6333"
    #         - "6334:6334"
    #     volumes:
    #         - qdrant-data:/qdrant/storage
    
    redis:
        image: redis:alpine
        container_name: my_redis
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - redis-data:/data
  
volumes:
    qdrant-data:
    redis-data:
